{{- if not .Values.integration.existingConfigSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kimo.fullname" . }}-backend-config
  labels:
    {{- include "kimo.labels" . | nindent 4 }}
type: Opaque
stringData:
  config: {{ .Values.integration.config | toJson | quote }}
{{- end }}
