apiVersion: v1
kind: Service
metadata:
  name: {{ include "kimo.fullname" . }}
  labels:
    {{- include "kimo.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "kimo.labels" . | nindent 4 }}
    control-plane: controller-manager
  ports:
    - name: api
      port: {{ .Values.api.port }}
      targetPort: api
      protocol: TCP
